id: PCD96BDCC
initial_creation_type: ocr
source_metadata:
  volumes:
    bd5be9e17f13437a8159f2cbbcca62d5:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: འཁྲུལ་པ་བཟློག་པའི་རིགས་པ་གཏན་ཚིགས་གྲུབ་པ།
      total_pages: 1605
      volume_number: 57
